/** DB 데이터 편집/조회 탭에서 사용하는 테이블·필드별 한국어 설명 */
export const DATA_EDITOR_FIELD_DESCRIPTIONS: Record<string, Record<string, string>> = {
  // ── 편집 가능 테이블 ─────────────────────────────────────
  SystemConfig: {
    key: "설정 키 (고유). 예: menuPermissions, jejuDepositAccount",
    value: "JSON 문자열. 메뉴 권한·제주 계좌·예약 불가일 등 저장",
    updatedAt: "마지막 수정 시각",
  },
  Team: {
    id: "팀 고유 ID (변경 불가)",
    name: "팀 표시명",
    sortOrder: "목록 정렬 순서 (작을수록 앞)",
    leaderId: "팀장으로 지정된 사원 ID",
    leaderName: "팀장 이름 (조회용)",
    createdAt: "생성 시각",
    updatedAt: "마지막 수정 시각",
  },
  AllocationSourceConfig: {
    id: "고유 ID (변경 불가)",
    sourceCode: "부여 구분 코드 (예: BASE_ANNUAL, CARE, TENURE_BONUS)",
    label: "화면 표시명",
    sortOrder: "정렬 순서",
    isActive: "사용 여부 (false면 귀속연도 초기화 시 제외)",
    defaultDays: "고정 부여일 수 (null이면 계산 로직 사용)",
    tenureYears: "근속 기준 연수 (TENURE_1Y·5Y·10Y 등에서 사용)",
    fiscalInitOnlyAfterGrantDate:
      "LeaveType 미사용·AllocationSourceConfig만 쓰는 근속 마일스톤: 귀속 초기화 시 기념일이 KST 오늘 이하여야만 보강(true 권장)",
    carryoverThresholdMonths: "이월 특례 기준 개월 수 (TENURE_1Y: 귀속연도 종료 N개월 전 부여분 이월)",
    bonusIntervalYears: "근속가산 부여 주기(년) (TENURE_BONUS에서 사용)",
    bonusMaxDays: "근속가산 최대 일수 상한",
    skipForFreelancer: "프리랜서 직원에게 미부여 여부",
    note: "비고",
    createdAt: "생성 시각",
    updatedAt: "마지막 수정 시각",
  },
  SchedulerJobType: {
    id: "고유 ID (변경 불가)",
    jobKey: "작업 키 (예: monthly_accrual, birthday_half, jeju_remind)",
    name: "표시명",
    description: "작업 설명",
    sortOrder: "정렬 순서",
    isActive: "스케줄러 활성화 여부 (false면 실행 안 됨)",
    createdAt: "생성 시각",
    updatedAt: "마지막 수정 시각",
  },

  // ── 읽기 전용 테이블 ─────────────────────────────────────
  Employee: {
    id: "사원 고유 ID",
    empNo: "사번 (예: E001)",
    name: "이름",
    teamId: "소속 팀 ID",
    position: "직급 (예: 대리, 과장)",
    dutyDept: "직무부서 (OPERATIONS·EDUCATION·WELFARE 중 하나, null=미배정)",
    employeeType: "고용 형태 (FULL=정규직, PART=파트타임, FREELANCE=프리랜서, EXTERNAL=외부)",
    hireDate: "입사일",
    birthDate: "생년월일",
    phone: "휴대폰번호 (AES-256 암호화 저장)",
    email: "이메일 주소 (AES-256 암호화 저장)",
    emailEnabled: "이메일 주소 유무와 동기(시스템 메일 차단 아님). 사원 저장 API가 주소 기준으로 맞춤",
    alimtalkEnabled: "카카오 알림톡 수신 여부",
    status: "재직 상태 (ACTIVE=재직, INVITED=초대됨, INACTIVE=퇴직)",
    role: "시스템 권한 (STAFF=일반, PM=팀장급, ADMIN=관리자)",
    createdAt: "생성 시각",
    updatedAt: "마지막 수정 시각",
  },
  User: {
    id: "계정 고유 ID",
    employeeId: "연결된 사원 ID",
    username: "로그인 아이디 (휴대폰 번호 숫자만)",
    passwordHash: "bcrypt 해시 비밀번호 (평문 노출 불가)",
    mustChangePassword: "다음 로그인 시 비밀번호 변경 강제 여부",
    lastLoginAt: "마지막 로그인 시각",
    createdAt: "계정 생성 시각",
    updatedAt: "마지막 수정 시각",
  },
  Notice: {
    id: "공지사항 고유 ID",
    title: "제목",
    content: "본문 (HTML 또는 Markdown)",
    authorId: "작성자 사원 ID",
    createdAt: "작성 시각",
    updatedAt: "마지막 수정 시각",
  },
  Form: {
    id: "양식 고유 ID",
    title: "양식 제목",
    slug: "URL용 슬러그 (고유, 예: survey-2025)",
    description: "양식 설명",
    isActive: "공개 여부 (false면 외부에서 접근 불가)",
    createdAt: "생성 시각",
    updatedAt: "마지막 수정 시각",
  },
  FormSubmission: {
    id: "제출 고유 ID",
    formId: "제출된 양식 ID",
    submitterName: "제출자 이름 (외부 입력)",
    submitterEmail: "제출자 이메일 (외부 입력)",
    submitterPhone: "제출자 연락처 (외부 입력)",
    createdAt: "제출 시각",
  },
  JejuAccommodation: {
    id: "신청 고유 ID",
    employeeId: "신청자 사원 ID",
    startDate: "숙박 시작일",
    endDate: "숙박 종료일",
    nights: "박 수",
    reason: "방문 목적/사유",
    guestName: "입금자명",
    guestPhone: "입금자 연락처",
    guestCount: "투숙 인원",
    depositorName: "입금자명 (별도 지정 시)",
    status: "신청 상태 (PENDING·APPROVED·REJECTED·CANCELLED)",
    step1ApproverId: "1차 결재자 사원 ID",
    step1ApprovedAt: "1차 결재 시각",
    rejectStep: "반려 발생 단계",
    approvedById: "최종 승인자 사원 ID",
    approvedAt: "최종 승인 시각",
    depositStatus: "입금 확인 상태 (PENDING·CONFIRMED)",
    depositConfirmedById: "입금 확인자 사원 ID",
    depositConfirmedAt: "입금 확인 시각",
    rejectComment: "반려 사유",
    cancelledAt: "취소 시각",
    cancelReason: "취소 사유",
    cancelRequestedAt: "취소 요청 시각",
    createdAt: "신청 생성 시각",
    updatedAt: "마지막 수정 시각",
  },
  LeaveRequest: {
    id: "휴가 신청 고유 ID",
    employeeId: "신청자 사원 ID",
    startDate: "휴가 시작일",
    endDate: "휴가 종료일",
    totalDays: "신청 총 일수 (반차=0.5)",
    reason: "휴가 사유",
    status: "진행 상태 (PENDING·APPROVED·REJECTED·CANCELLED)",
    currentStep: "현재 결재 단계 (1=1차, 2=최종 등)",
    totalSteps: "총 결재 단계 수",
    cancelledAt: "취소 처리 시각",
    cancelReason: "취소 사유",
    createdAt: "신청 시각",
    updatedAt: "마지막 수정 시각",
  },
  LeaveType: {
    id: "휴가 유형 고유 ID",
    code: "내부 코드 (예: ANNUAL, CARE, BIRTHDAY_HALF)",
    name: "표시명",
    daysPerUnit: "1회 부여 일수 (반차=0.5)",
    deductFromBalance: "잔여 일수에서 차감 여부",
    approvalSteps: "결재 단계 수",
    maxPerMonth: "월 최대 사용 일수 (null=제한없음)",
    maxPerYear: "연 최대 사용 일수 (null=제한없음)",
    requiresStamp: "스탬프 소모 필요 여부",
    stampCount: "소모 스탬프 수",
    allocationSourceCode: "연결된 할당 소스 코드 (AllocationSourceConfig.sourceCode)",
    usageCategory: "사용 분류 (ASSET=자산형, EVENT=이벤트형)",
    allowSameDay: "당일 신청 허용 여부",
    allowsFullDay: "종일 사용 허용 여부",
    allowsHalfDay: "반차 사용 허용 여부",
    halfDayAmPm: "반차 구분 (AM=오전, PM=오후, BOTH=모두)",
    includeInFiscalInit: "귀속연도 초기화 시 포함 여부",
    fiscalInitOnlyAfterGrantDate:
      "생일·입사주년형: 귀속 초기화 시 KST 오늘까지 부여일이 도래한 경우만 보강(true 권장). false면 FY 안 미래 일정도 초기화에 생성",
    hireAnniversaryYears: "입사 N주년 자동 부여 연수 (입사일기준 유형·allocationSourceCode와 함께 사용)",
    carryoverEligible: "휴가 할당에서 수동 이월(CARRYOVER) UI 허용 여부 (연차·근속가산 풀 등 정책 반영)",
    validityBasis: "유효 기간 기준 (귀속연도·입사일기준·부여일기준 등 한글 값)",
    validityMonths: "유효 기간(개월) - validityBasis가 GRANT_DATE일 때 사용",
    isActive: "사용 여부",
    sortOrder: "정렬 순서",
    color: "캘린더 표시 색상 코드",
    createdAt: "생성 시각",
    updatedAt: "마지막 수정 시각",
  },
  LeaveAllocation: {
    id: "할당 고유 ID",
    employeeId: "대상 사원 ID",
    sourceCode: "부여 구분 코드 (AllocationSourceConfig.sourceCode)",
    label: "표시명 (예: '기본연차', '돌봄휴가(이월)')",
    totalDays: "부여 총 일수",
    usedDays: "사용된 일수",
    validFrom: "사용 가능 시작일",
    validUntil: "사용 가능 종료일",
    fiscalYear: "귀속연도 (예: 2026 = 2026-05-01 ~ 2027-04-30)",
    note: "비고 (월별 적립 메타, 이월 출처 등 기록)",
    grantedById: "부여자 사원 ID (null=시스템 자동)",
    isActive: "활성 여부 (false=자동이월 등으로 대체된 원본)",
    createdAt: "생성 시각",
    updatedAt: "마지막 수정 시각",
  },
  AuditLog: {
    id: "로그 고유 ID",
    entityType: "대상 엔티티 종류 (예: Employee, LeaveRequest)",
    entityId: "대상 엔티티 ID",
    action: "수행된 작업 (CREATED·UPDATED·DELETED·APPROVED·REJECTED 등)",
    actorId: "작업 수행자 사원 ID",
    actorName: "작업 수행자 이름 (기록 시점)",
    before: "변경 전 데이터 (JSON)",
    after: "변경 후 데이터 (JSON)",
    note: "추가 설명",
    ip: "작업 수행자 IP 주소",
    createdAt: "로그 기록 시각",
  },
  SchedulerLog: {
    id: "로그 고유 ID",
    jobName: "스케줄러 작업명 (예: monthly_accrual)",
    targetParam: "작업 대상 파라미터 (예: 2026-04)",
    isDryRun: "드라이런(미리보기) 여부",
    status: "실행 결과 (SUCCESS·PARTIAL·FAILED)",
    grantedCount: "부여 성공 건수",
    skippedCount: "건너뜀 건수",
    errorCount: "오류 건수",
    detail: "상세 내용 (JSON)",
    triggeredBy: "실행 트리거 (SCHEDULER=자동, MANUAL=수동)",
    actorId: "수동 실행자 사원 ID (자동=null)",
    createdAt: "실행 시각",
  },
  NotificationLog: {
    id: "로그 고유 ID",
    targetId: "수신 대상 사원 ID",
    phone: "발송된 수신 번호",
    type: "알림 종류 (ALIMTALK·EMAIL 등)",
    templateCode: "카카오 알림톡 템플릿 코드",
    params: "템플릿 변수 (JSON)",
    status: "발송 결과 (SUCCESS·FAILED)",
    errorMsg: "오류 메시지 (실패 시)",
    sentAt: "발송 시각",
    createdAt: "생성 시각",
  },
  InviteToken: {
    id: "토큰 고유 ID",
    employeeId: "초대 대상 사원 ID",
    token: "초대 링크용 난수 토큰",
    expiresAt: "토큰 만료 시각",
    usedAt: "토큰 사용(계정 생성) 시각",
    createdAt: "생성 시각",
  },
  Holiday: {
    id: "공휴일 고유 ID",
    date: "공휴일 날짜",
    name: "공휴일 명칭 (예: 추석, 광복절)",
    isHalfDay: "반일 공휴일 여부",
    createdAt: "등록 시각",
  },
  StampRequest: {
    id: "스탬프 신청 고유 ID",
    employeeId: "신청자 사원 ID",
    stampDate: "근무 날짜",
    description: "근무 내용·사유",
    status: "진행 상태 (PENDING·APPROVED·REJECTED)",
    approverId: "결재자 사원 ID",
    approvedAt: "결재 처리 시각",
    comment: "결재 코멘트",
    stampId: "부여된 StampCoupon ID (승인 시 연결)",
    createdAt: "신청 시각",
  },
  StampCard: {
    id: "스탬프 카드 고유 ID",
    employeeId: "소유 사원 ID",
    sortOrder: "카드 정렬 순서",
    filledCount: "현재 채워진 스탬프 수",
    healingUsed: "치유 휴가 사용 여부",
    afternoonUsed: "오후 반차 사용 여부",
    healingLeaveRequestId: "치유 휴가 신청 ID",
    afternoonLeaveRequestId: "오후 반차 신청 ID",
    createdAt: "카드 생성 시각",
    updatedAt: "마지막 수정 시각",
  },
  LeaveApproval: {
    id: "결재 고유 ID",
    leaveRequestId: "연결된 휴가 신청 ID",
    approverId: "결재자 사원 ID",
    step: "결재 단계 번호 (1=1차, 2=최종 등)",
    status: "결재 상태 (PENDING·APPROVED·REJECTED)",
    comment: "결재 코멘트",
    approvedAt: "결재 처리 시각",
    createdAt: "결재 레코드 생성 시각",
  },
};

/** SystemConfig 키별 설명 (키 값에 대한 설명) */
export const SYSTEM_CONFIG_KEY_DESCRIPTIONS: Record<string, string> = {
  menuPermissions: "역할별 메뉴 접근 권한 JSON. { STAFF: [메뉴ID...], PM: [...], ADMIN: [...] }",
  /** 휴가 결재 시 PM 역할자 중 누구를 쓸지 고정할 때: Employee.id(cuid) 문자열 하나. 비우면 DB의 PM 역할 직원 중 findFirst */
  leaveApprovalPMId:
    "휴가 1단 결재에서 쓸 PM 지정: 값은 사원 Employee.id(cuid). 팀장 신청→이 사람이 결재, 팀원 신청 시 팀장 없으면 이 사람. 미설정 시 role=PM인 직원 중 임의 1명",
  jejuDepositAccount: "제주 숙소 예약금 입금 계좌 정보 JSON. { bankName, accountNumber, holderName }",
  jejuBlockedDates: "제주 숙소 예약 불가일 JSON. [\"YYYY-MM-DD\", ...]",
};
